# Generated by Django 4.1.1 on 2022-10-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_reporter_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('job', models.CharField(max_length=30)),
            ],
        ),
    ]
