# Generated by Django 4.1.1 on 2022-10-06 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_emp_add'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='emp_add',
            new_name='Reporter1',
        ),
    ]
