# Generated by Django 4.1.1 on 2022-10-06 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0007_rename_emp_add_reporter1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reporter1',
            new_name='Reporter_add',
        ),
    ]
